import { Events } from "../types/Events";

export const events: Events = {
  mainEvents: {
    impro: [
      {
        id: 1,
        dayOfWeek: 'Monday',
        date: '23.09',
        guestName: 'John',
        guestSurname: 'Doe',
        phone: '+123456721312349',
      },
      {
        id: 2,
        dayOfWeek: 'Tuesday',
        date: '22.09',
        guestName: 'John',
        guestSurname: 'Doe',
        phone: '+123456712349',
      },
      {
        id: 3,
        dayOfWeek: 'Monday',
        date: '23.09',
        guestName: 'John',
        guestSurname: 'Doe',
        phone: '+3456721312349',
      },

    ],
    playback: [
      {
        id: 1,
        dayOfWeek: 'Tuesday',
        date: '17.09',
        guestName: 'Jane',
        guestSurname: 'Smith',
        phone: '+987654321',
      },
    ],
    livePerf: [
      {
        id: 1,
        dayOfWeek: 'Wednesday',
        date: '18.09',
        guestName: 'Alice',
        guestSurname: 'Johnson',
        phone: '+1122334455',
      },
    ],
  },
  otherClasses: {
    heels: [
      {
        id: 1,
        dayOfWeek: 'Monday',
        date: '16.09',
        guestName: 'John',
        guestSurname: 'Doe',
        phone: '+1234556789',
      },
      {
        id: 2,
        dayOfWeek: 'Monday',
        date: '16.09',
        guestName: 'John',
        guestSurname: 'Doe',
        phone: '+1234456789',
      },
      {
        id: 3,
        dayOfWeek: 'Monday',
        date: '16.09',
        guestName: 'John',
        guestSurname: 'Doe',
        phone: '+1234526789',
      },
      {
        id: 4,
        dayOfWeek: 'Sunday',
        date: '21.09',
        guestName: 'John',
        guestSurname: 'Doe',
        phone: '+1231456789',
      },
    ],
    twerk: [
      {
        id: 1,
        dayOfWeek: 'Monday',
        date: '16.09',
        guestName: 'John',
        guestSurname: 'Doe',
        phone: '+123456781',
      },
      {
        id: 2,
        dayOfWeek: 'Monday',
        date: '16.09',
        guestName: 'John',
        guestSurname: 'Doe',
        phone: '+123456782',
      },
      {
        id: 3,
        dayOfWeek: 'Monday',
        date: '16.09',
        guestName: 'John',
        guestSurname: 'Doe',
        phone: '+123456783',
      },
      {
        id: 4,
        dayOfWeek: 'Sunday',
        date: '21.09',
        guestName: 'John',
        guestSurname: 'Doe',
        phone: '+123456784',
      },
    ],
    exotic: [
      {
        id: 1,
        dayOfWeek: 'Monday',
        date: '16.09',
        guestName: 'John',
        guestSurname: 'Doe',
        phone: '+12345655789',
      },
      {
        id: 2,
        dayOfWeek: 'Monday',
        date: '16.09',
        guestName: 'John',
        guestSurname: 'Doe',
        phone: '+12345666789',
      },
      {
        id: 3,
        dayOfWeek: 'Monday',
        date: '16.09',
        guestName: 'John',
        guestSurname: 'Doe',
        phone: '+123456556789',
      },
      {
        id: 4,
        dayOfWeek: 'Sunday',
        date: '21.09',
        guestName: 'John',
        guestSurname: 'Doe',
        phone: '+123453246789',
      },
    ],
    poleDance: [
      {
        id: 1,
        dayOfWeek: 'Monday',
        date: '16.09',
        guestName: 'John',
        guestSurname: 'Doe',
        phone: '+1235456789',
      },
      {
        id: 2,
        dayOfWeek: 'Tuesday',
        date: '24.09',
        guestName: 'John',
        guestSurname: 'Doe',
        phone: '+12434564789',
      },
    ],
    stretching: [
      {
        id: 1,
        dayOfWeek: 'Monday',
        date: '16.09',
        guestName: 'John',
        guestSurname: 'Doe',
        phone: '+12993456789',
      },
      {
        id: 2,
        dayOfWeek: 'Monday',
        date: '16.09',
        guestName: 'John',
        guestSurname: 'Doe',
        phone: '+12388456789',
      },
      {
        id: 3,
        dayOfWeek: 'Monday',
        date: '16.09',
        guestName: 'John',
        guestSurname: 'Doe',
        phone: '+123458796789',
      },
      {
        id: 4,
        dayOfWeek: 'Sunday',
        date: '21.09',
        guestName: 'John',
        guestSurname: 'Doe',
        phone: '+123455676789',
      },
    ],
  },
}